#baseURL = "http://example.org/"
#url: sfranck72.github.io
baseURL = "/"

#languageCode = "en-us"
languageCode = "fr"
title = "MSX-coding"

# Modifiez le thème pour qu'il soit utilisé par défaut à chaque génération de site.
theme = "hugo-theme-learn"

[params]
  # Modifier le schéma de couleur par défaut. Peut être "red", "blue", "green".
  themeVariant = "blue"

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON"]
